### ISSUE TITLE
Console not chatting

### ISSUE THREAD

**Issue by SnrSterling** [dominik-korsa/discord-integration#59]
The console channel does not write anything. It works, sends commands, but there is no answer. I did everything according to the instructions twice, but it does not work. What should I do to make the console respond?

Screen: https://i.imgur.com/8eVPTG8.png

**Comment by TheRedstoneRadiant** [comment]
Can reproduce. 

At a certain point, I could stop and start the server and it would send console output through the Discord bot to the channel, but now it isn't working at all. 

Commands go through when I type them:
![image](https://github.com/dominik-korsa/discord-integration/assets/76220359/b706caeb-a772-4eb3-9b8a-44481e37d48e)
![image](https://github.com/dominik-korsa/discord-integration/assets/76220359/f78543d0-c645-4bc9-8ff6-4e375de94318)

System Info: Java 18 (OpenJDK 64-Bit Server VM 18.0.2.1+1) Host: Linux 5.15.0-1032-oracle (aarch64)
Paper version git-Paper-524 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)

Plugins:
LuckPerms v5.4.79
DiscordIntegration v3.4.3 
WorldGuard v7.0.8-beta-01+cbb2ba7
WorldEdit v7.2.14+6360-094b734
WorldGuardEvents v1.18.1
floodgate v2.2.2-SNAPSHOT (b??-2702bc3)
Geyser-Spigot v2.1.0-SNAPSHOT
LifeSteal-Smp-Plugin v2.3.18

config.yml:
```yaml
# Do not edit the file-version!
file-version: 6

# Put your Discord token here:
discord-token: xxxxxxxxxxxxxxxxxxxxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxx
chat:
  channels:
  - '1103477660312682628'
  webhooks:
  - https://discord.com/api/webhooks/1203493394129524041/............
  console-channels:
  - '1203471022088338941'
  join:
    enabled: true
    as-embed: true
    color: 0x06d6a0
    # Whether to use player avatar and name as join message author
    player-as-author: true
  quit:
    enabled: true
    as-embed: true
    color: 0xef476f
    # Whether to use player avatar and name as quit message author
    player-as-author: true
  death:
    enabled: true
    as-embed: true
    color: 0xffd166
    # Whether to use player avatar and name as death message author
    player-as-author: true
  crash-embed:
    enabled: true
    color: 0xff8d0a
  avatar:
    # Set to true on cracked servers,
    # for premium player heads to work:
    offline-mode: false
    
    # URL of player's avatar, which will be used on Discord
    #
    # %player% is replaced by the player username
    # %uuid% is replaced by the player UUID,
    # if offline-mode is set to true, the plugin will use
    # the Mojang's API to get the correct UUID
    #
    # Use this url to show faces instead of heads:
    # https://crafatar.com/avatars/%uuid%?overlay
    url: https://crafatar.com/renders/head/%uuid%?overlay
  # You could try setting this to false, if messages sent by players
  # do not appear on Discord
  # This might be the case if you are using chat plugins, like VentureChat
  ignore-cancelled-chat-events: true
activity:
  # Interval (in seconds) of Discord activity updates
  # Activity is also updated every time a player enters or leaves the server
  # Please note that Discord allows up to 5 updates per 20 seconds
  update-interval: 60
  # Settings for %time% template
  time:
    world: world
    # Time is rounded down to the nearest multiple of this value
    # For example setting this to 15 will round the time to:
    # 10:00, 10:15, 10:30, 10:45, 11:00, 11:15 etc.
    # If the number doesn't divide an hour (60) the results might be unexpected
    round: 1
    # Whether to use 24-hour clock (true) or 12-hour clock (false)
    24h: true
  idle-when-no-players-online: true
linking:
  enabled: false
  # If set to true, users will now be able to join the game
  # without linking their Discord account
  mandatory: true
  
  # These roles are assigned to Discord members (except bots),
  # who have or have not linked their Minecraft profile
  # You must create these roles yourself
  #
  # Please note the role of your Discord bot must be higher
  # than the linked and not linked roles, otherwise the bot
  # will not be able to assign them
  linked-roles: null
  # - 0123456789
  not-linked-roles: null
  # - 0123456789

    # If set to true, the bot automatically set the nicknames
  # of Discord members to names of linked Minecraft players
  # You should remove "Change Nickname" permission from users
  # if this setting is enabled
  sync-nicknames: true
debug:
  # Will output each message received from Discord in server console
  log-discord-messages: false
  # Log a message each time a AsyncPlayerChatEvent is received,
  # but it has been cancelled by another plugin
  # Possible values:
  #   disable: Doesn't log any cancelled events
  #   auto:
  #     Logs cancelled chat events until at least one
  #     not-cancelled event is received, doesn't log anything
  #     if chat.ignore-cancelled-chat-events is set to false
  #   all: Logs all cancelled chat events
  log-cancelled-chat-events: disable
```
